baseURL = "/"
languageCode = "en-us"
title = "Cloud Native Day"
theme = ["nativeday"]

defaultContentLanguage = "en"
defaultContentLanguageInSubDir = true

[languages]
    [languages.en]
        languageName = "English"
        weight = 10
        contentDir = "content/english"

        [[languages.en.menu.main]]
            identifier = "about"
            name = "About"
            url = "/en/#about"
            weight = 20

        [[languages.en.menu.main]]
            identifier = "location"
            name = "Location"
            url = "/en/#location"
            weight = 30

        [[languages.en.menu.main]]
            identifier = "sponsors"
            name = "Sponsors"
            url = "/en/#sponsors"
            weight = 40

        [[languages.en.menu.main]]
            identifier = "program"
            name = "Program"
            url = "/en/program"
            weight = 50

        [[languages.en.menu.main]]
            identifier = "registration"
            name = "Registration"
            url = "https://www.eventbrite.ca/e/journee-cloud-native-montreal-cloud-native-day-montreal-tickets-57543465053"
            weight = 60
        
        [[languages.en.menu.main]]
            identifier = "contact-us"
            name = "Contact us"
            url = "mailto:ctrang@cloudops.com"
            weight = 70


        [[languages.en.menu.secondary]]
            identifier = "early-bird"
            name = "Early Bird Tickets"
            url = "https://www.eventbrite.ca/e/journee-cloud-native-montreal-cloud-native-day-montreal-tickets-57543465053"
            weight = 10

        [[languages.en.menu.secondary]]
            identifier = "call-for-proposals"
            name = "Call for Proposals"
            url = "mailto:ctrang@cloudops.com"
            weight = 20

        [[languages.en.menu.secondary]]
            identifier = "become-a-sponsor"
            name = "Become a Sponsor"
            url = "/en/program"
            weight = 30

    [languages.fr]
        languageName = "Français"
        weight = 10
        contentDir = "content/french"

        [[languages.fr.menu.main]]
            identifier = "about"
            name = "À propos"
            url = "/fr/#a-propos"
            weight = 20

        [[languages.fr.menu.main]]
            identifier = "location"
            name = "Lieu"
            url = "/fr/#lieu"
            weight = 30

        [[languages.fr.menu.main]]
            identifier = "sponsors"
            name = "Commanditaires"
            url = "/fr/#commanditaires"
            weight = 40

        [[languages.fr.menu.main]]
            identifier = "program"
            name = "Programmation"
            url = "/fr/programmation"
            weight = 50

        [[languages.fr.menu.main]]
            identifier = "registration"
            name = "Inscription"
            url = "https://www.eventbrite.ca/e/journee-cloud-native-montreal-cloud-native-day-montreal-tickets-57543465053"
            weight = 60

        [[languages.fr.menu.main]]
            identifier = "contact-us"
            name = "Nous joindre"
            url = "mailto:ctrang@cloudops.com"
            weight = 70


        [[languages.fr.menu.secondary]]
            identifier = "early-bird"
            name = "Billets Pré-inscription"
            url = "https://www.eventbrite.ca/e/journee-cloud-native-montreal-cloud-native-day-montreal-tickets-57543465053"
            weight = 10

        [[languages.fr.menu.secondary]]
            identifier = "call-for-proposals"
            name = "Appels à propositions"
            url = "mailto:ctrang@cloudops.com"
            weight = 20

        [[languages.fr.menu.secondary]]
            identifier = "become-a-sponsor"
            name = "Devenir un Commanditaire"
            url = "/fr/programmation"
            weight = 30